first = int(input("Give me the first number: "))
second = int(input("Give me the second number: "))
print("Thank you!")
print(f"{first} + {second} = {first+second}")
print(f"{first} - {second} = {first-second}")
print(f"{first} / {second} = {int(first/second)}")
print(f"{first} * {second} = {first*second}")